###############################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

FROM gcr.io/google.com/cloudsdktool/google-cloud-cli

ARG GO_VERSION=1.19.2
ENV PATH="${PATH}:/usr/local/go/bin"

RUN apt-get update >/dev/null
RUN apt-get -y install build-essential unzip

# Install Docker
# See: https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh ./get-docker.sh >/dev/null

# Install Go
# See: https://go.dev/doc/install
RUN curl -OL https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz
RUN sha256sum go$GO_VERSION.linux-amd64.tar.gz
RUN tar -C /usr/local -xvf go$GO_VERSION.linux-amd64.tar.gz
RUN rm go$GO_VERSION.linux-amd64.tar.gz
RUN go version

#Install kubectl
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl \
    && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
    && chmod +x get_helm.sh && ./get_helm.sh > /dev/null

#Install Terraform
RUN curl -OL https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
RUN unzip terraform_1.3.3_linux_amd64.zip
RUN mv terraform /usr/local/bin

#Install GoLint
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1

# Install Java
RUN apt-get install openjdk-11-jdk -y >/dev/null
RUN java -version


