/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins { id 'org.apache.beam.module' }

applyJavaNature(
  automaticModuleName: 'org.apache.beam.sdk.extensions.sql.meta.provider.delta',
  requireJavaVersion: JavaVersion.VERSION_17,
)

description = "Apache Beam :: SDKs :: Java :: Extensions :: SQL :: Delta Lake"
ext.summary = "Delta Lake table provider for Beam SQL."

dependencies {
  implementation project(":sdks:java:extensions:sql")
  implementation project(":sdks:java:core")
  implementation project(":sdks:java:managed")
  implementation project(":sdks:java:io:delta")
  implementation library.java.jackson_databind
  implementation library.java.jackson_core
  implementation library.java.slf4j_api
  implementation library.java.vendored_guava_32_1_2_jre
  implementation library.java.vendored_calcite_1_40_0
  // TODO(https://github.com/apache/beam/issues/21156): Determine how to build without this dependency
  provided "org.immutables:value:2.8.8"
  permitUnusedDeclared "org.immutables:value:2.8.8"
  permitUnusedDeclared project(":sdks:java:io:delta")
  permitUnusedDeclared library.java.slf4j_api

  testImplementation library.java.joda_time
  testImplementation library.java.junit
  testImplementation library.java.hadoop_common
  testImplementation project(path: ":sdks:java:io:delta", configuration: "testRuntimeMigration")
  testImplementation project(path: ":runners:direct-java", configuration: "shadow")
}
