BEAM_ROOT_DIR_ENV_VAR_KEY = "BEAM_ROOT_DIR"
BEAM_EXAMPLE_CATEGORIES_ENV_VAR_KEY = "BEAM_EXAMPLE_CATEGORIES"

SERVER_ADDRESS_ENV_VAR_KEY = "SERVER_ADDRESS"
SDK_CONFIG_ENV_VAR_KEY = "SDK_CONFIG"

BEAM_USE_WEBGRPC_ENV_VAR_KEY = 'BEAM_USE_WEBGRPC'
GRPC_TIMEOUT_ENV_VAR_KEY = "GRPC_TIMEOUT"
