state_bucket = "beam_playground_terraform"
state_prefix = "memorystore/"
vpc_name     = "default"
examples_bucket_name = "playground-precompiled-objects"
service_account = " playground-deploy@apache-beam-testing.iam.gserviceaccount.com"