/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.beam.sdk.runners;

import static org.hamcrest.Matchers.containsInAnyOrder;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.not;
import static org.junit.Assert.assertThat;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.apache.beam.sdk.Pipeline.PipelineVisitor;
import org.apache.beam.sdk.io.CountingInput;
import org.apache.beam.sdk.io.CountingInput.BoundedCountingInput;
import org.apache.beam.sdk.io.CountingSource;
import org.apache.beam.sdk.io.Read;
import org.apache.beam.sdk.testing.TestPipeline;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PBegin;
import org.apache.beam.sdk.values.PCollection;
import org.apache.beam.sdk.values.PValue;
import org.hamcrest.Matchers;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

/**
 * Tests for {@link TransformHierarchy}.
 */
@RunWith(JUnit4.class)
public class TransformHierarchyTest implements Serializable {
  @Rule public transient ExpectedException thrown = ExpectedException.none();
  private transient TransformHierarchy hierarchy;
  private transient TestPipeline pipeline;

  @Before
  public void setup() {
    hierarchy = new TransformHierarchy();
    pipeline = TestPipeline.create();
  }

  @Test
  public void getCurrentNoPushReturnsRoot() {
    assertThat(hierarchy.getCurrent().isRootNode(), is(true));
  }

  @Test
  public void popWithoutPushThrows() {
    thrown.expect(IllegalStateException.class);
    hierarchy.popNode();
  }

  @Test
  public void pushThenPopSucceeds() {
    TransformTreeNode root = hierarchy.getCurrent();
    TransformTreeNode node =
        new TransformTreeNode(hierarchy.getCurrent(), Create.of(1), "Create", PBegin.in(pipeline));
    hierarchy.pushNode(node);
    assertThat(hierarchy.getCurrent(), equalTo(node));
    hierarchy.popNode();
    assertThat(hierarchy.getCurrent(), equalTo(root));
  }

  @Test
  public void replaceSetsReplacedNode() {
    TransformTreeNode root = hierarchy.getCurrent();
    PBegin begin = PBegin.in(pipeline);
    Create.Values<Long> create = Create.of(0L);
    PCollection<Long> created = pipeline.apply("Create", create);
    TransformTreeNode original = new TransformTreeNode(root, create, "Create", begin);
    original.setOutput(created);
    root.addComposite(original);

    BoundedCountingInput replacement = CountingInput.upTo(1L);
    PCollection<Long> counted = pipeline.apply(replacement);
    TransformTreeNode replacementNode = new TransformTreeNode(root, replacement, "Counting", begin);
    replacementNode.setOutput(counted);

    hierarchy.pushNode(original);
    hierarchy.popNode();

    hierarchy.replaceNode(original, replacementNode);
    assertThat(replacementNode.getOutput(), equalTo(original.getOutput()));
    assertThat(replacementNode.getReplaced(), equalTo(original));
  }

  @Test
  public void visitVisitsAllPushed() {
    TransformTreeNode root = hierarchy.getCurrent();

    // This is a fake composite used to demonstrate properties of the TransformTreeNodes, and does
    // not represent the actual Pipeline generated by applying the transform expansions.
    Create.Values<Long> create = Create.of(1L);
    Read.Bounded<Long> count = Read.from(CountingSource.upTo(1L));
    PBegin begin = PBegin.in(pipeline);
    PCollection<Long> counted = begin.apply(count);

    final TransformTreeNode compositeNode =
        new TransformTreeNode(root, create, "Create", begin);
    compositeNode.setOutput(counted);
    root.addComposite(compositeNode);

    TransformTreeNode primitiveNode =
        new TransformTreeNode(
            compositeNode, count, "Create/Read", begin);
    primitiveNode.setOutput(counted);
    compositeNode.addComposite(primitiveNode);

    ParDo.Bound<Long, Long> mapElements =
        ParDo.of(
            new DoFn<Long, Long>() {
              @ProcessElement
              public void apply(ProcessContext ctxt) {
                ctxt.output(ctxt.element());
              }
            });
    PCollection<Long> mapped = counted.apply(mapElements);
    TransformTreeNode otherPrimitive = new TransformTreeNode(root, mapElements, "ParDo", counted);
    root.addComposite(otherPrimitive);
    otherPrimitive.setOutput(mapped);
    otherPrimitive.addInputProducer(counted, primitiveNode);

    hierarchy.pushNode(compositeNode);
    hierarchy.pushNode(primitiveNode);
    hierarchy.popNode();
    hierarchy.popNode();
    hierarchy.pushNode(otherPrimitive);
    hierarchy.popNode();

    final Set<TransformTreeNode> visitedCompositeNodes = new HashSet<>();
    final Set<TransformTreeNode> visitedPrimitiveNodes = new HashSet<>();
    final Set<PValue> visitedValuesInVisitor = new HashSet<>();

    Set<PValue> visitedValues = new HashSet<>();
    hierarchy.visit(new PipelineVisitor.Defaults() {
      @Override
      public CompositeBehavior enterCompositeTransform(TransformTreeNode node) {
        visitedCompositeNodes.add(node);
        return CompositeBehavior.ENTER_TRANSFORM;
      }

      @Override
      public void visitPrimitiveTransform(TransformTreeNode node) {
        visitedPrimitiveNodes.add(node);
      }

      @Override
      public void visitValue(PValue value, TransformTreeNode producer) {
        visitedValuesInVisitor.add(value);
      }
    }, visitedValues);

    assertThat(
        "All composites should have been visited",
        visitedCompositeNodes,
        containsInAnyOrder(root, compositeNode));
    assertThat(
        "All primitives should have been visited",
        visitedPrimitiveNodes,
        containsInAnyOrder(primitiveNode, otherPrimitive));
    assertThat(
        "All expanded POutputs should have been visited",
        visitedValuesInVisitor,
        Matchers.<PValue>containsInAnyOrder(counted, mapped));
  }

  @Test
  public void visitAfterReplaceVisitsOnlyReplacement() {
    TransformTreeNode root = hierarchy.getCurrent();
    PBegin begin = PBegin.in(pipeline);
    Create.Values<Long> create = Create.of(0L);
    PCollection<Long> created = pipeline.apply("Create", create);
    final TransformTreeNode original = new TransformTreeNode(root, create, "Create", begin);
    original.setOutput(created);
    root.addComposite(original);

    BoundedCountingInput replacement = CountingInput.upTo(1L);
    final PCollection<Long> counted = pipeline.apply(replacement);
    TransformTreeNode replacementNode = new TransformTreeNode(root, replacement, "Counting", begin);
    replacementNode.setOutput(counted);

    hierarchy.pushNode(original);
    hierarchy.popNode();

    hierarchy.replaceNode(original, replacementNode);

    final Set<PValue> visitedValues = new HashSet<>();
    final Set<TransformTreeNode> visitedTransforms = new HashSet<>();
    hierarchy.visit(
        new PipelineVisitor.Defaults() {
          @Override
          public CompositeBehavior enterCompositeTransform(TransformTreeNode node) {
            visitedTransforms.add(node);
            return CompositeBehavior.ENTER_TRANSFORM;
          }

          @Override
          public void visitPrimitiveTransform(TransformTreeNode node) {
            visitedTransforms.add(node);
          }

          @Override
          public void visitValue(PValue value, TransformTreeNode producer) {
            assertThat(
                "The original producer should not have produced any output",
                producer,
                not(equalTo(original)));
            assertThat(
                "The replacement node's generated output should not be in the hierarchy",
                value,
                not(Matchers.<PValue>equalTo(counted)));
            visitedValues.add(value);
          }
        },
        new HashSet<PValue>());

    assertThat(visitedTransforms, containsInAnyOrder(root, replacementNode));
    assertThat(visitedValues, Matchers.<PValue>containsInAnyOrder(created));
  }
}
