"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Protocol Buffers for metrics classes, used in the Fn API, Job API, and by SDKs.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MonitoringInfoSpec(_message.Message):
    """A specification for describing a well known MonitoringInfo.

    All specifications are uniquely identified by the urn.
    """

    DESCRIPTOR: _descriptor.Descriptor

    URN_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    REQUIRED_LABELS_FIELD_NUMBER: _builtins.int
    ANNOTATIONS_FIELD_NUMBER: _builtins.int
    urn: _builtins.str
    """Defines the semantic meaning of the metric or monitored state.

    See MonitoringInfoSpecs.Enum for the set of well known metrics/monitored
    state.
    """
    type: _builtins.str
    """Defines the required encoding and aggregation method for the payload.

    See MonitoringInfoTypeUrns.Enum for the set of well known types.
    """
    @_builtins.property
    def required_labels(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The list of required labels for the specified urn and type."""

    @_builtins.property
    def annotations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Annotation]:
        """Extra non functional parts of the spec for descriptive purposes.
        i.e. description, units, etc.
        """

    def __init__(
        self,
        *,
        urn: _builtins.str | None = ...,
        type: _builtins.str | None = ...,
        required_labels: _abc.Iterable[_builtins.str] | None = ...,
        annotations: _abc.Iterable[Global___Annotation] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["annotations", b"annotations", "required_labels", b"required_labels", "type", b"type", "urn", b"urn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MonitoringInfoSpec: _TypeAlias = MonitoringInfoSpec  # noqa: Y015

@_typing.final
class Annotation(_message.Message):
    """The key name and value string of MonitoringInfo annotations."""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str | None = ...,
        value: _builtins.str | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Annotation: _TypeAlias = Annotation  # noqa: Y015

@_typing.final
class MonitoringInfoSpecs(_message.Message):
    """A set of well known MonitoringInfo specifications."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Enum:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EnumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MonitoringInfoSpecs._Enum.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        USER_SUM_INT64: MonitoringInfoSpecs._Enum.ValueType  # 0
        """Represents an integer counter where values are summed across bundles."""
        USER_SUM_DOUBLE: MonitoringInfoSpecs._Enum.ValueType  # 1
        """Represents a double counter where values are summed across bundles."""
        USER_DISTRIBUTION_INT64: MonitoringInfoSpecs._Enum.ValueType  # 2
        """Represents a distribution of an integer value where:
          - count: represents the number of values seen across all bundles
          - sum: represents the total of the value across all bundles
          - min: represents the smallest value seen across all bundles
          - max: represents the largest value seen across all bundles
        """
        USER_DISTRIBUTION_DOUBLE: MonitoringInfoSpecs._Enum.ValueType  # 3
        """Represents a distribution of a double value where:
          - count: represents the number of values seen across all bundles
          - sum: represents the total of the value across all bundles
          - min: represents the smallest value seen across all bundles
          - max: represents the largest value seen across all bundles
        """
        USER_LATEST_INT64: MonitoringInfoSpecs._Enum.ValueType  # 4
        """Represents the latest seen integer value. The timestamp is used to
        provide an "ordering" over multiple values to determine which is the
        latest.
        """
        USER_LATEST_DOUBLE: MonitoringInfoSpecs._Enum.ValueType  # 5
        """Represents the latest seen double value. The timestamp is used to
        provide an "ordering" over multiple values to determine which is the
        latest.
        """
        USER_TOP_N_INT64: MonitoringInfoSpecs._Enum.ValueType  # 6
        """Represents the largest set of integer values seen across bundles."""
        USER_TOP_N_DOUBLE: MonitoringInfoSpecs._Enum.ValueType  # 7
        """Represents the largest set of double values seen across bundles."""
        USER_BOTTOM_N_INT64: MonitoringInfoSpecs._Enum.ValueType  # 8
        """Represents the smallest set of integer values seen across bundles."""
        USER_BOTTOM_N_DOUBLE: MonitoringInfoSpecs._Enum.ValueType  # 9
        """Represents the smallest set of double values seen across bundles."""
        USER_SET_STRING: MonitoringInfoSpecs._Enum.ValueType  # 21
        """Represents a set of strings seen across bundles."""
        USER_BOUNDED_TRIE: MonitoringInfoSpecs._Enum.ValueType  # 22
        """Represents a set of strings seen across bundles."""
        ELEMENT_COUNT: MonitoringInfoSpecs._Enum.ValueType  # 10
        """General monitored state information which contains structured information
        which does not fit into a typical metric format. See MonitoringTableData
        for more details.

        TODO(https://github.com/apache/beam/issues/20122): Support monitored state.

        USER_MONITORING_TABLE = XX [(monitoring_info_spec) = {
          urn: "beam:metric:user:v1",
          type: "beam:metrics:monitoring_table:v1",
          required_labels: ["PTRANSFORM", "NAMESPACE", "NAME"],
          annotations: [{
            key: "description",
            value: "URN utilized to report user monitoring data."
          }]
        }];
        """
        SAMPLED_BYTE_SIZE: MonitoringInfoSpecs._Enum.ValueType  # 11
        START_BUNDLE_MSECS: MonitoringInfoSpecs._Enum.ValueType  # 12
        PROCESS_BUNDLE_MSECS: MonitoringInfoSpecs._Enum.ValueType  # 13
        FINISH_BUNDLE_MSECS: MonitoringInfoSpecs._Enum.ValueType  # 14
        TOTAL_MSECS: MonitoringInfoSpecs._Enum.ValueType  # 15
        WORK_REMAINING: MonitoringInfoSpecs._Enum.ValueType  # 16
        """All values reported across all beam:metric:ptransform_progress:.*:v1
        metrics are of the same magnitude.
        """
        WORK_COMPLETED: MonitoringInfoSpecs._Enum.ValueType  # 17
        """All values reported across all beam:metric:ptransform_progress:.*:v1
        metrics are of the same magnitude.
        """
        DATA_CHANNEL_READ_INDEX: MonitoringInfoSpecs._Enum.ValueType  # 18
        """The (0-based) index of the latest item processed from the data channel.
        This gives an indication of the SDKs progress through the data channel,
        and is a lower bound on where it is able to split.
        For an SDK that processes items sequentially, this is equivalently the
        number of items fully processed (or -1 if processing has not yet started).
        """
        API_REQUEST_COUNT: MonitoringInfoSpecs._Enum.ValueType  # 19
        API_REQUEST_LATENCIES: MonitoringInfoSpecs._Enum.ValueType  # 20
        USER_HISTOGRAM: MonitoringInfoSpecs._Enum.ValueType  # 23

    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper): ...
    USER_SUM_INT64: MonitoringInfoSpecs.Enum.ValueType  # 0
    """Represents an integer counter where values are summed across bundles."""
    USER_SUM_DOUBLE: MonitoringInfoSpecs.Enum.ValueType  # 1
    """Represents a double counter where values are summed across bundles."""
    USER_DISTRIBUTION_INT64: MonitoringInfoSpecs.Enum.ValueType  # 2
    """Represents a distribution of an integer value where:
      - count: represents the number of values seen across all bundles
      - sum: represents the total of the value across all bundles
      - min: represents the smallest value seen across all bundles
      - max: represents the largest value seen across all bundles
    """
    USER_DISTRIBUTION_DOUBLE: MonitoringInfoSpecs.Enum.ValueType  # 3
    """Represents a distribution of a double value where:
      - count: represents the number of values seen across all bundles
      - sum: represents the total of the value across all bundles
      - min: represents the smallest value seen across all bundles
      - max: represents the largest value seen across all bundles
    """
    USER_LATEST_INT64: MonitoringInfoSpecs.Enum.ValueType  # 4
    """Represents the latest seen integer value. The timestamp is used to
    provide an "ordering" over multiple values to determine which is the
    latest.
    """
    USER_LATEST_DOUBLE: MonitoringInfoSpecs.Enum.ValueType  # 5
    """Represents the latest seen double value. The timestamp is used to
    provide an "ordering" over multiple values to determine which is the
    latest.
    """
    USER_TOP_N_INT64: MonitoringInfoSpecs.Enum.ValueType  # 6
    """Represents the largest set of integer values seen across bundles."""
    USER_TOP_N_DOUBLE: MonitoringInfoSpecs.Enum.ValueType  # 7
    """Represents the largest set of double values seen across bundles."""
    USER_BOTTOM_N_INT64: MonitoringInfoSpecs.Enum.ValueType  # 8
    """Represents the smallest set of integer values seen across bundles."""
    USER_BOTTOM_N_DOUBLE: MonitoringInfoSpecs.Enum.ValueType  # 9
    """Represents the smallest set of double values seen across bundles."""
    USER_SET_STRING: MonitoringInfoSpecs.Enum.ValueType  # 21
    """Represents a set of strings seen across bundles."""
    USER_BOUNDED_TRIE: MonitoringInfoSpecs.Enum.ValueType  # 22
    """Represents a set of strings seen across bundles."""
    ELEMENT_COUNT: MonitoringInfoSpecs.Enum.ValueType  # 10
    """General monitored state information which contains structured information
    which does not fit into a typical metric format. See MonitoringTableData
    for more details.

    TODO(https://github.com/apache/beam/issues/20122): Support monitored state.

    USER_MONITORING_TABLE = XX [(monitoring_info_spec) = {
      urn: "beam:metric:user:v1",
      type: "beam:metrics:monitoring_table:v1",
      required_labels: ["PTRANSFORM", "NAMESPACE", "NAME"],
      annotations: [{
        key: "description",
        value: "URN utilized to report user monitoring data."
      }]
    }];
    """
    SAMPLED_BYTE_SIZE: MonitoringInfoSpecs.Enum.ValueType  # 11
    START_BUNDLE_MSECS: MonitoringInfoSpecs.Enum.ValueType  # 12
    PROCESS_BUNDLE_MSECS: MonitoringInfoSpecs.Enum.ValueType  # 13
    FINISH_BUNDLE_MSECS: MonitoringInfoSpecs.Enum.ValueType  # 14
    TOTAL_MSECS: MonitoringInfoSpecs.Enum.ValueType  # 15
    WORK_REMAINING: MonitoringInfoSpecs.Enum.ValueType  # 16
    """All values reported across all beam:metric:ptransform_progress:.*:v1
    metrics are of the same magnitude.
    """
    WORK_COMPLETED: MonitoringInfoSpecs.Enum.ValueType  # 17
    """All values reported across all beam:metric:ptransform_progress:.*:v1
    metrics are of the same magnitude.
    """
    DATA_CHANNEL_READ_INDEX: MonitoringInfoSpecs.Enum.ValueType  # 18
    """The (0-based) index of the latest item processed from the data channel.
    This gives an indication of the SDKs progress through the data channel,
    and is a lower bound on where it is able to split.
    For an SDK that processes items sequentially, this is equivalently the
    number of items fully processed (or -1 if processing has not yet started).
    """
    API_REQUEST_COUNT: MonitoringInfoSpecs.Enum.ValueType  # 19
    API_REQUEST_LATENCIES: MonitoringInfoSpecs.Enum.ValueType  # 20
    USER_HISTOGRAM: MonitoringInfoSpecs.Enum.ValueType  # 23

    def __init__(
        self,
    ) -> None: ...

Global___MonitoringInfoSpecs: _TypeAlias = MonitoringInfoSpecs  # noqa: Y015

@_typing.final
class MonitoringInfoLabelProps(_message.Message):
    """A set of properties for the MonitoringInfoLabel, this is useful to obtain
    the proper label string for the MonitoringInfoLabel.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The label key to use in the MonitoringInfo labels map."""
    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MonitoringInfoLabelProps: _TypeAlias = MonitoringInfoLabelProps  # noqa: Y015

@_typing.final
class MonitoringInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _MonitoringInfoLabels:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MonitoringInfoLabelsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MonitoringInfo._MonitoringInfoLabels.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        TRANSFORM: MonitoringInfo._MonitoringInfoLabels.ValueType  # 0
        """The values used for TRANSFORM, PCOLLECTION, WINDOWING_STRATEGY
        CODER, ENVIRONMENT, etc. must always match the keys used to
        refer to them. For actively processed bundles, these should match the
        values within the ProcessBundleDescriptor. For job management APIs,
        these should match values within the original pipeline representation.
        """
        PCOLLECTION: MonitoringInfo._MonitoringInfoLabels.ValueType  # 1
        WINDOWING_STRATEGY: MonitoringInfo._MonitoringInfoLabels.ValueType  # 2
        CODER: MonitoringInfo._MonitoringInfoLabels.ValueType  # 3
        ENVIRONMENT: MonitoringInfo._MonitoringInfoLabels.ValueType  # 4
        NAMESPACE: MonitoringInfo._MonitoringInfoLabels.ValueType  # 5
        NAME: MonitoringInfo._MonitoringInfoLabels.ValueType  # 6
        SERVICE: MonitoringInfo._MonitoringInfoLabels.ValueType  # 7
        METHOD: MonitoringInfo._MonitoringInfoLabels.ValueType  # 8
        RESOURCE: MonitoringInfo._MonitoringInfoLabels.ValueType  # 9
        STATUS: MonitoringInfo._MonitoringInfoLabels.ValueType  # 10
        BIGQUERY_PROJECT_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 11
        BIGQUERY_DATASET: MonitoringInfo._MonitoringInfoLabels.ValueType  # 12
        BIGQUERY_TABLE: MonitoringInfo._MonitoringInfoLabels.ValueType  # 13
        BIGQUERY_VIEW: MonitoringInfo._MonitoringInfoLabels.ValueType  # 14
        BIGQUERY_QUERY_NAME: MonitoringInfo._MonitoringInfoLabels.ValueType  # 15
        GCS_BUCKET: MonitoringInfo._MonitoringInfoLabels.ValueType  # 16
        GCS_PROJECT_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 17
        DATASTORE_PROJECT: MonitoringInfo._MonitoringInfoLabels.ValueType  # 18
        DATASTORE_NAMESPACE: MonitoringInfo._MonitoringInfoLabels.ValueType  # 19
        BIGTABLE_PROJECT_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 20
        INSTANCE_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 21
        TABLE_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 22
        SPANNER_PROJECT_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 23
        SPANNER_DATABASE_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 24
        SPANNER_TABLE_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 25
        SPANNER_INSTANCE_ID: MonitoringInfo._MonitoringInfoLabels.ValueType  # 26
        SPANNER_QUERY_NAME: MonitoringInfo._MonitoringInfoLabels.ValueType  # 27
        PER_WORKER_METRIC: MonitoringInfo._MonitoringInfoLabels.ValueType  # 28
        """Label which if has a "true" value indicates that the metric is intended
        to be aggregated per-worker.
        """

    class MonitoringInfoLabels(_MonitoringInfoLabels, metaclass=_MonitoringInfoLabelsEnumTypeWrapper): ...
    TRANSFORM: MonitoringInfo.MonitoringInfoLabels.ValueType  # 0
    """The values used for TRANSFORM, PCOLLECTION, WINDOWING_STRATEGY
    CODER, ENVIRONMENT, etc. must always match the keys used to
    refer to them. For actively processed bundles, these should match the
    values within the ProcessBundleDescriptor. For job management APIs,
    these should match values within the original pipeline representation.
    """
    PCOLLECTION: MonitoringInfo.MonitoringInfoLabels.ValueType  # 1
    WINDOWING_STRATEGY: MonitoringInfo.MonitoringInfoLabels.ValueType  # 2
    CODER: MonitoringInfo.MonitoringInfoLabels.ValueType  # 3
    ENVIRONMENT: MonitoringInfo.MonitoringInfoLabels.ValueType  # 4
    NAMESPACE: MonitoringInfo.MonitoringInfoLabels.ValueType  # 5
    NAME: MonitoringInfo.MonitoringInfoLabels.ValueType  # 6
    SERVICE: MonitoringInfo.MonitoringInfoLabels.ValueType  # 7
    METHOD: MonitoringInfo.MonitoringInfoLabels.ValueType  # 8
    RESOURCE: MonitoringInfo.MonitoringInfoLabels.ValueType  # 9
    STATUS: MonitoringInfo.MonitoringInfoLabels.ValueType  # 10
    BIGQUERY_PROJECT_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 11
    BIGQUERY_DATASET: MonitoringInfo.MonitoringInfoLabels.ValueType  # 12
    BIGQUERY_TABLE: MonitoringInfo.MonitoringInfoLabels.ValueType  # 13
    BIGQUERY_VIEW: MonitoringInfo.MonitoringInfoLabels.ValueType  # 14
    BIGQUERY_QUERY_NAME: MonitoringInfo.MonitoringInfoLabels.ValueType  # 15
    GCS_BUCKET: MonitoringInfo.MonitoringInfoLabels.ValueType  # 16
    GCS_PROJECT_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 17
    DATASTORE_PROJECT: MonitoringInfo.MonitoringInfoLabels.ValueType  # 18
    DATASTORE_NAMESPACE: MonitoringInfo.MonitoringInfoLabels.ValueType  # 19
    BIGTABLE_PROJECT_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 20
    INSTANCE_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 21
    TABLE_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 22
    SPANNER_PROJECT_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 23
    SPANNER_DATABASE_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 24
    SPANNER_TABLE_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 25
    SPANNER_INSTANCE_ID: MonitoringInfo.MonitoringInfoLabels.ValueType  # 26
    SPANNER_QUERY_NAME: MonitoringInfo.MonitoringInfoLabels.ValueType  # 27
    PER_WORKER_METRIC: MonitoringInfo.MonitoringInfoLabels.ValueType  # 28
    """Label which if has a "true" value indicates that the metric is intended
    to be aggregated per-worker.
    """

    @_typing.final
    class LabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str | None = ...,
            value: _builtins.str | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    URN_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    LABELS_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    urn: _builtins.str
    """(Required) Defines the semantic meaning of the metric or monitored state.

    See MonitoringInfoSpecs.Enum for the set of well known metrics/monitored
    state.
    """
    type: _builtins.str
    """(Required) Defines the encoding and aggregation method for the payload.

    See MonitoringInfoTypeUrns.Enum for the set of well known types.
    """
    payload: _builtins.bytes
    """(Required) The metric or monitored state encoded as per the specification
    defined by the type.
    """
    @_builtins.property
    def labels(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """A set of key and value labels which define the scope of the metric. For
        well known URNs, the set of required labels is provided by the associated
        MonitoringInfoSpec.

        Either a well defined entity id for matching the enum names in
        the MonitoringInfoLabels enum or any arbitrary label
        set by a custom metric or user metric.

        A monitoring system is expected to be able to aggregate the metrics
        together for all updates having the same URN and labels. Some systems such
        as Stackdriver will be able to aggregate the metrics using a subset of the
        provided labels
        """

    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """This indicates the start of the time range over which this value was
        measured.
        This is needed by some external metric aggregation services
        to indicate when the reporter of the metric first began collecting the
        cumulative value for the timeseries.
        If the SDK Harness restarts, it should reset the start_time, and reset
        the collection of cumulative metrics (i.e. start to count again from 0).
        HarnessMonitoringInfos should set this start_time once, when the
        MonitoringInfo is first reported.
        ProcessBundle MonitoringInfos should set a start_time for each bundle.
        """

    def __init__(
        self,
        *,
        urn: _builtins.str | None = ...,
        type: _builtins.str | None = ...,
        payload: _builtins.bytes | None = ...,
        labels: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        start_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["labels", b"labels", "payload", b"payload", "start_time", b"start_time", "type", b"type", "urn", b"urn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MonitoringInfo: _TypeAlias = MonitoringInfo  # noqa: Y015

@_typing.final
class MonitoringInfoTypeUrns(_message.Message):
    """A set of well known URNs that specify the encoding and aggregation method."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Enum:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EnumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MonitoringInfoTypeUrns._Enum.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUM_INT64_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 0
        """Represents an integer counter where values are summed across bundles.

        Encoding: <value>
          - value: beam:coder:varint:v1
        """
        SUM_DOUBLE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 1
        """Represents a double counter where values are summed across bundles.

        Encoding: <value>
          value: beam:coder:double:v1
        """
        DISTRIBUTION_INT64_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 2
        """Represents a distribution of an integer value where:
          - count: represents the number of values seen across all bundles
          - sum: represents the total of the value across all bundles
          - min: represents the smallest value seen across all bundles
          - max: represents the largest value seen across all bundles

        Encoding: <count><sum><min><max>
          - count: beam:coder:varint:v1
          - sum:   beam:coder:varint:v1
          - min:   beam:coder:varint:v1
          - max:   beam:coder:varint:v1

        Note that when count is zero, the SDK may not send sum, min, and max in
        the response. If those fields are included in the payload, runners should
        omit them.
        """
        DISTRIBUTION_DOUBLE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 3
        """Represents a distribution of a double value where:
          - count: represents the number of values seen across all bundles
          - sum: represents the total of the value across all bundles
          - min: represents the smallest value seen across all bundles
          - max: represents the largest value seen across all bundles

        Encoding: <count><sum><min><max>
          - count: beam:coder:varint:v1
          - sum:   beam:coder:double:v1
          - min:   beam:coder:double:v1
          - max:   beam:coder:double:v1

        Note that when count is zero, the SDK may not send sum, min, and max in
        the response. If those fields are included in the payload, runners should
        omit them.
        """
        LATEST_INT64_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 4
        """Represents the latest seen integer value. The timestamp is used to
        provide an "ordering" over multiple values to determine which is the
        latest.

        Encoding: <timestamp><value>
          - timestamp: beam:coder:varint:v1     (milliseconds since epoch)
          - value:     beam:coder:varint:v1
        """
        LATEST_DOUBLE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 5
        """Represents the latest seen double value. The timestamp is used to
        provide an "ordering" over multiple values to determine which is the
        latest.

        Encoding: <timestamp><value>
          - timestamp: beam:coder:varint:v1     (milliseconds since epoch)
          - value:     beam:coder:double:v1
        """
        TOP_N_INT64_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 6
        """Represents the largest set of integer values seen across bundles.

        Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder:varint:v1
        """
        TOP_N_DOUBLE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 7
        """Represents the largest set of double values seen across bundles.

        Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder<beam:coder:double:v1
        """
        BOTTOM_N_INT64_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 8
        """Represents the smallest set of integer values seen across bundles.

        Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder:varint:v1
        """
        BOTTOM_N_DOUBLE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 9
        """Represents the smallest set of double values seen across bundles.

        Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder:double:v1
        """
        PROGRESS_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 10
        """Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder:double:v1
        """
        SET_STRING_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 11
        """Represents a set of strings.

        Encoding: <iter><value1><value2>...<valueN></iter>
          - iter:   beam:coder:iterable:v1
          - valueX: beam:coder:stringutf8:v1
        """
        BOUNDED_TRIE_TYPE: MonitoringInfoTypeUrns._Enum.ValueType  # 12
        """Represents a bounded trie of strings.

        Encoding: BoundedTrie proto
        """
        HISTOGRAM: MonitoringInfoTypeUrns._Enum.ValueType  # 13
        """Represents a histogram."""

    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper): ...
    SUM_INT64_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 0
    """Represents an integer counter where values are summed across bundles.

    Encoding: <value>
      - value: beam:coder:varint:v1
    """
    SUM_DOUBLE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 1
    """Represents a double counter where values are summed across bundles.

    Encoding: <value>
      value: beam:coder:double:v1
    """
    DISTRIBUTION_INT64_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 2
    """Represents a distribution of an integer value where:
      - count: represents the number of values seen across all bundles
      - sum: represents the total of the value across all bundles
      - min: represents the smallest value seen across all bundles
      - max: represents the largest value seen across all bundles

    Encoding: <count><sum><min><max>
      - count: beam:coder:varint:v1
      - sum:   beam:coder:varint:v1
      - min:   beam:coder:varint:v1
      - max:   beam:coder:varint:v1

    Note that when count is zero, the SDK may not send sum, min, and max in
    the response. If those fields are included in the payload, runners should
    omit them.
    """
    DISTRIBUTION_DOUBLE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 3
    """Represents a distribution of a double value where:
      - count: represents the number of values seen across all bundles
      - sum: represents the total of the value across all bundles
      - min: represents the smallest value seen across all bundles
      - max: represents the largest value seen across all bundles

    Encoding: <count><sum><min><max>
      - count: beam:coder:varint:v1
      - sum:   beam:coder:double:v1
      - min:   beam:coder:double:v1
      - max:   beam:coder:double:v1

    Note that when count is zero, the SDK may not send sum, min, and max in
    the response. If those fields are included in the payload, runners should
    omit them.
    """
    LATEST_INT64_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 4
    """Represents the latest seen integer value. The timestamp is used to
    provide an "ordering" over multiple values to determine which is the
    latest.

    Encoding: <timestamp><value>
      - timestamp: beam:coder:varint:v1     (milliseconds since epoch)
      - value:     beam:coder:varint:v1
    """
    LATEST_DOUBLE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 5
    """Represents the latest seen double value. The timestamp is used to
    provide an "ordering" over multiple values to determine which is the
    latest.

    Encoding: <timestamp><value>
      - timestamp: beam:coder:varint:v1     (milliseconds since epoch)
      - value:     beam:coder:double:v1
    """
    TOP_N_INT64_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 6
    """Represents the largest set of integer values seen across bundles.

    Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder:varint:v1
    """
    TOP_N_DOUBLE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 7
    """Represents the largest set of double values seen across bundles.

    Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder<beam:coder:double:v1
    """
    BOTTOM_N_INT64_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 8
    """Represents the smallest set of integer values seen across bundles.

    Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder:varint:v1
    """
    BOTTOM_N_DOUBLE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 9
    """Represents the smallest set of double values seen across bundles.

    Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder:double:v1
    """
    PROGRESS_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 10
    """Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder:double:v1
    """
    SET_STRING_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 11
    """Represents a set of strings.

    Encoding: <iter><value1><value2>...<valueN></iter>
      - iter:   beam:coder:iterable:v1
      - valueX: beam:coder:stringutf8:v1
    """
    BOUNDED_TRIE_TYPE: MonitoringInfoTypeUrns.Enum.ValueType  # 12
    """Represents a bounded trie of strings.

    Encoding: BoundedTrie proto
    """
    HISTOGRAM: MonitoringInfoTypeUrns.Enum.ValueType  # 13
    """Represents a histogram."""

    def __init__(
        self,
    ) -> None: ...

Global___MonitoringInfoTypeUrns: _TypeAlias = MonitoringInfoTypeUrns  # noqa: Y015

@_typing.final
class BoundedTrieNode(_message.Message):
    """A single node in a BoundedTrie."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ChildrenEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___BoundedTrieNode: ...
        def __init__(
            self,
            *,
            key: _builtins.str | None = ...,
            value: Global___BoundedTrieNode | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TRUNCATED_FIELD_NUMBER: _builtins.int
    CHILDREN_FIELD_NUMBER: _builtins.int
    truncated: _builtins.bool
    """Whether this node has been truncated.
    A truncated leaf represents possibly many children with the same prefix.
    """
    @_builtins.property
    def children(self) -> _containers.MessageMap[_builtins.str, Global___BoundedTrieNode]:
        """Children of this node.  Must be empty if truncated is true."""

    def __init__(
        self,
        *,
        truncated: _builtins.bool | None = ...,
        children: _abc.Mapping[_builtins.str, Global___BoundedTrieNode] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["children", b"children", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoundedTrieNode: _TypeAlias = BoundedTrieNode  # noqa: Y015

@_typing.final
class BoundedTrie(_message.Message):
    """The message type used for encoding metrics of type bounded trie."""

    DESCRIPTOR: _descriptor.Descriptor

    BOUND_FIELD_NUMBER: _builtins.int
    ROOT_FIELD_NUMBER: _builtins.int
    SINGLETON_FIELD_NUMBER: _builtins.int
    bound: _builtins.int
    """The maximum number of elements to store before truncation."""
    @_builtins.property
    def root(self) -> Global___BoundedTrieNode:
        """A compact representation of all the elements in this trie."""

    @_builtins.property
    def singleton(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A more efficient representation for metrics consisting of a single value."""

    def __init__(
        self,
        *,
        bound: _builtins.int | None = ...,
        root: Global___BoundedTrieNode | None = ...,
        singleton: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["root", b"root"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bound", b"bound", "root", b"root", "singleton", b"singleton"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoundedTrie: _TypeAlias = BoundedTrie  # noqa: Y015

@_typing.final
class HistogramValue(_message.Message):
    """The message type used for encoding Histogram Data"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class BucketOptions(_message.Message):
        """`BucketOptions` describes the bucket boundaries used in the histogram."""

        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class Linear(_message.Message):
            """Linear buckets with the following boundaries for indices in 0 to n-1.
            - i in [0, n-1]:  [start + (i)*width, start + (i+1)*width)
            """

            DESCRIPTOR: _descriptor.Descriptor

            NUMBER_OF_BUCKETS_FIELD_NUMBER: _builtins.int
            WIDTH_FIELD_NUMBER: _builtins.int
            START_FIELD_NUMBER: _builtins.int
            number_of_buckets: _builtins.int
            """Must be greater than 0.

            (-- api-linter: core::0140::prepositions=disabled
                aip.dev/not-precedent: `bucket_count` would cause confusion with
                `bucket_counts` field --)
            """
            width: _builtins.float
            """Distance between bucket boundaries. Must be greater than 0."""
            start: _builtins.float
            """Lower bound of the first bucket."""
            def __init__(
                self,
                *,
                number_of_buckets: _builtins.int | None = ...,
                width: _builtins.float | None = ...,
                start: _builtins.float | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets", "_start", b"_start", "_width", b"_width", "number_of_buckets", b"number_of_buckets", "start", b"start", "width", b"width"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets", "_start", b"_start", "_width", b"_width", "number_of_buckets", b"number_of_buckets", "start", b"start", "width", b"width"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType__number_of_buckets: _TypeAlias = _typing.Literal["number_of_buckets"]  # noqa: Y015
            _WhichOneofArgType__number_of_buckets: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets"]  # noqa: Y015
            _WhichOneofReturnType__start: _TypeAlias = _typing.Literal["start"]  # noqa: Y015
            _WhichOneofArgType__start: _TypeAlias = _typing.Literal["_start", b"_start"]  # noqa: Y015
            _WhichOneofReturnType__width: _TypeAlias = _typing.Literal["width"]  # noqa: Y015
            _WhichOneofArgType__width: _TypeAlias = _typing.Literal["_width", b"_width"]  # noqa: Y015
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__number_of_buckets) -> _WhichOneofReturnType__number_of_buckets | None: ...
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__start) -> _WhichOneofReturnType__start | None: ...
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__width) -> _WhichOneofReturnType__width | None: ...

        @_typing.final
        class Base2Exponent(_message.Message):
            """Exponential buckets where the growth factor between buckets is
            `2**(2**-scale)`. e.g. for `scale=1` growth factor is
            `2**(2**(-1))=sqrt(2)`. `n` buckets will have the following boundaries.
             - 0th: [0, gf)
             - i in [1, n-1]: [gf^(i), gf^(i+1))
            """

            DESCRIPTOR: _descriptor.Descriptor

            NUMBER_OF_BUCKETS_FIELD_NUMBER: _builtins.int
            SCALE_FIELD_NUMBER: _builtins.int
            number_of_buckets: _builtins.int
            """Must be greater than 0.

            (-- api-linter: core::0140::prepositions=disabled
                aip.dev/not-precedent: `bucket_count` would cause confusion with
                `bucket_counts` field --)
            """
            scale: _builtins.int
            """Must be between -3 and 3. This forces the growth factor of the bucket
            boundaries to be between `2^(1/8)` and `256`.
            """
            def __init__(
                self,
                *,
                number_of_buckets: _builtins.int | None = ...,
                scale: _builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets", "_scale", b"_scale", "number_of_buckets", b"number_of_buckets", "scale", b"scale"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets", "_scale", b"_scale", "number_of_buckets", b"number_of_buckets", "scale", b"scale"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            _WhichOneofReturnType__number_of_buckets: _TypeAlias = _typing.Literal["number_of_buckets"]  # noqa: Y015
            _WhichOneofArgType__number_of_buckets: _TypeAlias = _typing.Literal["_number_of_buckets", b"_number_of_buckets"]  # noqa: Y015
            _WhichOneofReturnType__scale: _TypeAlias = _typing.Literal["scale"]  # noqa: Y015
            _WhichOneofArgType__scale: _TypeAlias = _typing.Literal["_scale", b"_scale"]  # noqa: Y015
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__number_of_buckets) -> _WhichOneofReturnType__number_of_buckets | None: ...
            @_typing.overload
            def WhichOneof(self, oneof_group: _WhichOneofArgType__scale) -> _WhichOneofReturnType__scale | None: ...

        LINEAR_FIELD_NUMBER: _builtins.int
        EXPONENTIAL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def linear(self) -> Global___HistogramValue.BucketOptions.Linear:
            """Bucket boundaries grow linearly."""

        @_builtins.property
        def exponential(self) -> Global___HistogramValue.BucketOptions.Base2Exponent:
            """Bucket boundaries grow exponentially."""

        def __init__(
            self,
            *,
            linear: Global___HistogramValue.BucketOptions.Linear | None = ...,
            exponential: Global___HistogramValue.BucketOptions.Base2Exponent | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["bucket_type", b"bucket_type", "exponential", b"exponential", "linear", b"linear"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket_type", b"bucket_type", "exponential", b"exponential", "linear", b"linear"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_bucket_type: _TypeAlias = _typing.Literal["linear", "exponential"]  # noqa: Y015
        _WhichOneofArgType_bucket_type: _TypeAlias = _typing.Literal["bucket_type", b"bucket_type"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_bucket_type) -> _WhichOneofReturnType_bucket_type | None: ...

    COUNT_FIELD_NUMBER: _builtins.int
    BUCKET_OPTIONS_FIELD_NUMBER: _builtins.int
    BUCKET_COUNTS_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    """Number of values recorded in this histogram."""
    @_builtins.property
    def bucket_options(self) -> Global___HistogramValue.BucketOptions:
        """Describes the bucket boundaries used in the histogram."""

    @_builtins.property
    def bucket_counts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The number of values in each bucket of the histogram, as described in
        `bucket_options`. `bucket_counts` should contain N values, where N is the
        number of buckets specified in `bucket_options`. If `bucket_counts` has
        fewer than N values, the remaining values are assumed to be 0.
        """

    def __init__(
        self,
        *,
        count: _builtins.int | None = ...,
        bucket_options: Global___HistogramValue.BucketOptions | None = ...,
        bucket_counts: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bucket_options", b"_bucket_options", "_count", b"_count", "bucket_options", b"bucket_options", "count", b"count"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bucket_options", b"_bucket_options", "_count", b"_count", "bucket_counts", b"bucket_counts", "bucket_options", b"bucket_options", "count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bucket_options: _TypeAlias = _typing.Literal["bucket_options"]  # noqa: Y015
    _WhichOneofArgType__bucket_options: _TypeAlias = _typing.Literal["_bucket_options", b"_bucket_options"]  # noqa: Y015
    _WhichOneofReturnType__count: _TypeAlias = _typing.Literal["count"]  # noqa: Y015
    _WhichOneofArgType__count: _TypeAlias = _typing.Literal["_count", b"_count"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bucket_options) -> _WhichOneofReturnType__bucket_options | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__count) -> _WhichOneofReturnType__count | None: ...

Global___HistogramValue: _TypeAlias = HistogramValue  # noqa: Y015

LABEL_PROPS_FIELD_NUMBER: _builtins.int
MONITORING_INFO_SPEC_FIELD_NUMBER: _builtins.int
label_props: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___MonitoringInfoLabelProps]
"""From: commit 0x7970544."""
monitoring_info_spec: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___MonitoringInfoSpec]
"""Enum extension to store the MonitoringInfoSpecs."""
