require 'fileutils'
require 'html-proofer'
require 'etc'

task :test do
  HTMLProofer.check_directory("./generated-local-content", {
    :typhoeus => {
      :timeout => 120,
      :connecttimeout => 90,
    },
    :allow_hash_href => true,
    :check_html => true,
    :file_ignore => [/v2/],
    :url_ignore => [
        # To ignore link checking for a URL, i.e. if it is temporariliy down,
        # add a URL regex below with a tracking JIRA issue. For example:
        # /example.com/, # BEAM-1234 failing due to expired SSL cert
    ],
    :parallel => { :in_processes => 4 },
    }).run
end
