require 'fileutils'
require 'html-proofer'
require 'etc'

task :test do
  HTMLProofer.check_directory("./content", {
    :typhoeus => {
      :timeout => 60,
      :connecttimeout => 40 },
    :allow_hash_href => true,
    :check_html => true,
    :file_ignore => [/javadoc/, /v2/, /pydoc/],
    :url_ignore => [
        # Javadocs and Pydocs are only available on asf-site branch
        /documentation\/sdks\/javadoc/,
        /documentation\/sdks\/pydoc/,

        /jstorm.io/,
        /datatorrent.com/,
        /ai.google/ # https://issues.apache.org/jira/browse/INFRA-16527
    ],
    :parallel => { :in_processes => Etc.nprocessors },
    }).run
end
