// Mocks generated by Mockito 5.3.2 from annotations
// in playground_components/test/src/controllers/playground_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:playground_components/src/cache/example_cache.dart' as _i9;
import 'package:playground_components/src/controllers/example_loaders/example_loader_factory.dart'
    as _i2;
import 'package:playground_components/src/controllers/example_loaders/examples_loader.dart'
    as _i4;
import 'package:playground_components/src/controllers/playground_controller.dart'
    as _i5;
import 'package:playground_components/src/models/category_with_examples.dart'
    as _i10;
import 'package:playground_components/src/models/example.dart' as _i3;
import 'package:playground_components/src/models/example_base.dart' as _i14;
import 'package:playground_components/src/models/example_loading_descriptors/examples_loading_descriptor.dart'
    as _i7;
import 'package:playground_components/src/models/example_view_options.dart'
    as _i12;
import 'package:playground_components/src/models/loading_status.dart' as _i11;
import 'package:playground_components/src/models/sdk.dart' as _i8;
import 'package:playground_components/src/models/snippet_file.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExampleLoaderFactory_0 extends _i1.SmartFake
    implements _i2.ExampleLoaderFactory {
  _FakeExampleLoaderFactory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExample_1 extends _i1.SmartFake implements _i3.Example {
  _FakeExample_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExamplesLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamplesLoader extends _i1.Mock implements _i4.ExamplesLoader {
  MockExamplesLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExampleLoaderFactory get defaultFactory => (super.noSuchMethod(
        Invocation.getter(#defaultFactory),
        returnValue: _FakeExampleLoaderFactory_0(
          this,
          Invocation.getter(#defaultFactory),
        ),
      ) as _i2.ExampleLoaderFactory);
  @override
  void setPlaygroundController(_i5.PlaygroundController? value) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaygroundController,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<void> loadIfNew(_i7.ExamplesLoadingDescriptor? descriptor) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadIfNew,
          [descriptor],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> load(_i7.ExamplesLoadingDescriptor? descriptor) =>
      (super.noSuchMethod(
        Invocation.method(
          #load,
          [descriptor],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> loadDefaultIfAny(_i8.Sdk? sdk) => (super.noSuchMethod(
        Invocation.method(
          #loadDefaultIfAny,
          [sdk],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ExampleCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockExampleCache extends _i1.Mock implements _i9.ExampleCache {
  MockExampleCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i8.Sdk, List<_i10.CategoryWithExamples>> get categoryListsBySdk =>
      (super.noSuchMethod(
        Invocation.getter(#categoryListsBySdk),
        returnValue: <_i8.Sdk, List<_i10.CategoryWithExamples>>{},
      ) as Map<_i8.Sdk, List<_i10.CategoryWithExamples>>);
  @override
  Map<_i8.Sdk, _i3.Example> get defaultExamplesBySdk => (super.noSuchMethod(
        Invocation.getter(#defaultExamplesBySdk),
        returnValue: <_i8.Sdk, _i3.Example>{},
      ) as Map<_i8.Sdk, _i3.Example>);
  @override
  bool get isSelectorOpened => (super.noSuchMethod(
        Invocation.getter(#isSelectorOpened),
        returnValue: false,
      ) as bool);
  @override
  set isSelectorOpened(bool? _isSelectorOpened) => super.noSuchMethod(
        Invocation.setter(
          #isSelectorOpened,
          _isSelectorOpened,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<void> get allExamplesFuture => (super.noSuchMethod(
        Invocation.getter(#allExamplesFuture),
        returnValue: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i11.LoadingStatus get catalogStatus => (super.noSuchMethod(
        Invocation.getter(#catalogStatus),
        returnValue: _i11.LoadingStatus.loading,
      ) as _i11.LoadingStatus);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> loadAllPrecompiledObjectsIfNot() => (super.noSuchMethod(
        Invocation.method(
          #loadAllPrecompiledObjectsIfNot,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  List<_i10.CategoryWithExamples> getCategories(_i8.Sdk? sdk) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [sdk],
        ),
        returnValue: <_i10.CategoryWithExamples>[],
      ) as List<_i10.CategoryWithExamples>);
  @override
  _i6.Future<_i3.Example> getPrecompiledObject(
    String? path,
    _i8.Sdk? sdk,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrecompiledObject,
          [
            path,
            sdk,
          ],
        ),
        returnValue: _i6.Future<_i3.Example>.value(_FakeExample_1(
          this,
          Invocation.method(
            #getPrecompiledObject,
            [
              path,
              sdk,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Example>);
  @override
  _i6.Future<_i3.Example> loadSharedExample(
    String? id, {
    required _i12.ExampleViewOptions? viewOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadSharedExample,
          [id],
          {#viewOptions: viewOptions},
        ),
        returnValue: _i6.Future<_i3.Example>.value(_FakeExample_1(
          this,
          Invocation.method(
            #loadSharedExample,
            [id],
            {#viewOptions: viewOptions},
          ),
        )),
      ) as _i6.Future<_i3.Example>);
  @override
  _i6.Future<String> saveSnippet({
    required List<_i13.SnippetFile>? files,
    required _i8.Sdk? sdk,
    required String? pipelineOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSnippet,
          [],
          {
            #files: files,
            #sdk: sdk,
            #pipelineOptions: pipelineOptions,
          },
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i3.Example> loadExampleInfo(_i14.ExampleBase? example) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadExampleInfo,
          [example],
        ),
        returnValue: _i6.Future<_i3.Example>.value(_FakeExample_1(
          this,
          Invocation.method(
            #loadExampleInfo,
            [example],
          ),
        )),
      ) as _i6.Future<_i3.Example>);
  @override
  void setSelectorOpened(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setSelectorOpened,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i3.Example?> getDefaultExampleBySdk(_i8.Sdk? sdk) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultExampleBySdk,
          [sdk],
        ),
        returnValue: _i6.Future<_i3.Example?>.value(),
      ) as _i6.Future<_i3.Example?>);
  @override
  _i6.Future<void> loadDefaultPrecompiledObjects() => (super.noSuchMethod(
        Invocation.method(
          #loadDefaultPrecompiledObjects,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> loadDefaultPrecompiledObjectsIfNot() => (super.noSuchMethod(
        Invocation.method(
          #loadDefaultPrecompiledObjectsIfNot,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<_i14.ExampleBase?> getCatalogExampleByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCatalogExampleByPath,
          [path],
        ),
        returnValue: _i6.Future<_i14.ExampleBase?>.value(),
      ) as _i6.Future<_i14.ExampleBase?>);
  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
