# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This workflow modifies the GCP User Roles when the infra/users.yml file is updated.
# It applies the changes using Terraform to manage the IAM roles for users defined in the users.yml
# If the workflow is triggered by a pull request, it will post the Terraform plan as a comment on the PR
# as a code block for easy review.

name: Modify the GCP User Roles according to the infra/users.yml file

on:
  workflow_run:
    workflows: ["Extract users.yml from PR"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  beam_UserRoles:
    name: Apply user roles changes
    runs-on: [self-hosted, ubuntu-24.04, main]
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout trusted base repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pr-data
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      # Move the users.yml file to the correct location for Terraform to process it
      - name: Prepare users.yml
        run: mv users.yml infra/iam/users.yml

      - name: Load PR Number
        run: |
          PR_NUM=$(cat pr_number.txt)
          echo "PR_NUMBER=$PR_NUM" >> $GITHUB_ENV

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db

      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: 1.12.2

      - name: Initialize Terraform
        working-directory: ./infra/iam
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/iam
        run: terraform plan -out=tfplan

      - name: Convert plan to plaintext
        working-directory: ./infra/iam
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Create comment body
        run: |
          PLAN_SIZE=$(wc -c < ./infra/iam/tfplan.txt)
          if [ "$PLAN_SIZE" -gt 60000 ]; then
            echo "### Terraform Plan for User Roles Changes" > comment_body.txt
            echo "Plan is too big, review in Github Action Logs" >> comment_body.txt
          else
            echo "### Terraform Plan for User Roles Changes" > comment_body.txt
            echo '```' >> comment_body.txt
            cat ./infra/iam/tfplan.txt >> comment_body.txt
            echo '```' >> comment_body.txt
          fi

      # Use the environment variable PR_NUMBER that we read from the file
      - name: Upload plan as a comment to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr comment "$PR_NUMBER" --body-file comment_body.txt
